### ISSUE TITLE
フッターデザインにSNSアイコン埋め込み

### ISSUE THREAD

**Issue by yuyu31** [gakusyutai/gakusyutai.github.io#2]

**Comment by Yuhki-Kimura** [comment]
1/12
[今回したこと]
Twitterのロゴ利用ガイドラインの理解、実際にロゴを入れてみる

[次回すること]
ロゴを踏むと、楽習隊の公式Twitterに飛べるようにするための方法を探す＆実践

**Comment by Yuhki-Kimura** [comment]
1/19
[今回したこと]
Twitterロゴに楽習隊アカウントのリンクを埋め込み

[気づき]
・文字であれ画像であれ、リンクを埋め込むなら
<a href="リンク">　[埋め込みたい文章や画像]　</a>
でできる。

[次回すること]
ロゴの大きさ調整とInstagramロゴのガイドラインを探す・読む
もう少しおしゃれなやつも作れたら作りたい（カーソル合わせると、ロゴが若干薄くなるとか濃くなるとか...）

**Comment by Yuhki-Kimura** [comment]
↑↑↑
(補足　1/19)

でできる

[気づき]
issueでもHTMLのコードを書くと、コードの内容が反映されてしまう

**Comment by Yuhki-Kimura** [comment]
↑↑↑
(補足2 1/19)
＜a href="リンク"＞[埋め込みたい文章や画像]＜/a＞

[気づき]
＜!--- ---＞もメモとして認識されて表示されなくなる。
投稿する前にきちんとpreviewを確認しよう。

**Comment by yuyu31** [comment]
（メッセージは編集、返信の形態をとることも可能です。）

**Comment by yuyu31** [comment]
> 1/19 [今回したこと] Twitterロゴに楽習隊アカウントのリンクを埋め込み
> 
> [気づき] ・文字であれ画像であれ、リンクを埋め込むなら [　[埋め込みたい文章や画像]　](リンク) でできる。
> 
> [次回すること] ロゴの大きさ調整とInstagramロゴのガイドラインを探す・読む もう少しおしゃれなやつも作れたら作りたい（カーソル合わせると、ロゴが若干薄くなるとか濃くなるとか...）

カーソルを合わせると挙動が変化するアニメーションに関して、すぐに思いつく方法は css で hover というプロパティを用いるやり方。
参考：https://developer.mozilla.org/ja/docs/Web/CSS/:hover

ロゴ自体の色の透明度を操作することもよいですが、仮にライセンスに引っ掛かってしまう場合、ロゴの背部の色（html のブロックレベル要素で画定させたブロック範囲？）の透明度を操作することも一つの選択肢になりそうです。デザイン的にどちらが良いかはわからないので適宜試しつつで。

**Comment by yuyu31** [comment]
> > 1/19 [今回したこと] Twitterロゴに楽習隊アカウントのリンクを埋め込み
> > [気づき] ・文字であれ画像であれ、リンクを埋め込むなら [　[埋め込みたい文章や画像]　](%E3%83%AA%E3%83%B3%E3%82%AF) でできる。
> > [次回すること] ロゴの大きさ調整とInstagramロゴのガイドラインを探す・読む もう少しおしゃれなやつも作れたら作りたい（カーソル合わせると、ロゴが若干薄くなるとか濃くなるとか...）
> 
> カーソルを合わせると挙動が変化するアニメーションに関して、すぐに思いつく方法は css で hover というプロパティを用いるやり方。 参考：https://developer.mozilla.org/ja/docs/Web/CSS/:hover
> 
> ロゴ自体の色の透明度を操作することもよいですが、仮にライセンスに引っ掛かってしまう場合、ロゴの背部の色（html のブロックレベル要素で画定させたブロック範囲？）の透明度を操作することも一つの選択肢になりそうです。デザイン的にどちらが良いかはわからないので適宜試しつつで。

**Comment by Yuhki-Kimura** [comment]
2/23
[今回したこと]
・Twitterのアカウントが新しくなったことに伴う、リンクの変更
・インスタのロゴ追加、リンク貼り付け
[気づき]
インスタもロゴのガイドラインは、ほぼTwitterと同じ
<a href="https://about.meta.com/ja/brand/resources/instagram/instagram-brand/">Instagramロゴガイドライン</a>

**Comment by yuyu31** [comment]
![image](https://user-images.githubusercontent.com/84178710/222324450-ee523dd1-7d47-49f0-9dc0-48249525730f.png)

**Comment by yuyu31** [comment]
フッター部分に少し編集を加えました。temporary ファイルを更新しておくのでローカルに反映させておいてください。
